### ISSUE TITLE
get ERDDAP back up

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#30]
* [x] pick a physical server to use as ERDDAP server : dune [[ref](https://github.com/USF-IMARS/server-status/commit/2cd994a11c91ee718ae4ce0d87a2ed39ac9b5bc5)]
* [x] create new imars-objects subdir for each ERDDAP product on the ERDDAP server [[ref](https://github.com/USF-IMARS/IMaRS-docs/blob/master/docs/management_data/imars-objects/checklist_create-chunk.md)]
* [x] create (or update) {dataset_name}.md here
* [x] rsync files from /fk/ or wherever to new location
* [x] update datasets.xml config to point to local dirs 
* [ ] email Dan

**Comment by 7yl4r** [comment]
related: https://github.com/USF-IMARS/imars_puppet_v3/issues/3

started the rsync:

```
[root@dune puppetlabs]# rsync -hazv /srv/imars-objects/fk/MEAN_7D_MODA/OC/* /mnt/sdb/moda_oc_7d_fk/. | tee ~/moda_oc_7d_fk-manual_rsync-2022_11_18.log
sending incremental file list
MODA_2002185_2002189_7D_FK_OC.nc
MODA_2002190_2002196_7D_FK_OC.nc
MODA_2002197_2002203_7D_FK_OC.nc
MODA_2002204_2002210_7D_FK_OC.nc
MODA_2002219_2002224_7D_FK_OC.nc
MODA_2002225_2002231_7D_FK_OC.nc
MODA_2002233_2002238_7D_FK_OC.nc
[...]
```

-------------------

I just restarted the docker container with the new config.
It should be able to load the dataset even as files are still streaming in.

**Comment by 7yl4r** [comment]
It works! :raised_hands: 

@dotis : we need to choose one of the ways to work with this on the processing server you use:

1. use NFS to access the data on the ERDDAP server directly
2. copy the data from the processing server to the ERDDAP server whenver it needs updating

(1) is nice because no duplication of data means less disk usage & less confusion.

On the ohter hand the duplicate data in (2) means that reprocessing & testing can happen while leaving the previous version of the data up.

**Comment by dotis** [comment]
Excellent. I think for now, we should perhaps write the 7D mean files to two places. I can write them to the current directory and keep things consistent and I can also write a set to the ERDDAP server.

We could streamline later if needed. Do you have a path for the ERDDAP server?

Thanks,
________________________________

**Comment by 7yl4r** [comment]
This is the command to run on dune that copies your files to the ERDDAP location:

```
rsync -hazv /srv/imars-objects/fk/MEAN_7D_MODA/OC/* /mnt/sdb/moda_oc_7d_fk/.
```

To run this on manglillo (or seashell) I think you can do:

```
rsync -hazv /srv/imars-objects/fk/MEAN_7D_MODA/OC/* dotis@dune:/mnt/sdb/moda_oc_7d_fk/.
```

If that works without issue then we can schedule the rsync command in your crontab.

**Comment by dotis** [comment]
Ok. I am going to get the dashboard files up and current again this week and will try this command. I have had some inquiries from NOAA and their Iconic Reef Program. They seem like a good potential end-user. I may add some extraction points/boxes at the Iconic Reef sites. Or, I suppose we could even develop an "Iconic Reef" dash if there is enough interest. Will Google charges go up as we add more boards?

Thanks!
________________________________

**Comment by 7yl4r** [comment]
Google charges go up as we add more *servers*. So far we have been doing one board per server, but we should consider putting multiple boards onto one server. I think we can use one SE-US server to host the dashboards for FKNMS, FWC, and this new project.

**Comment by dotis** [comment]
This is what happened when I tried the rsync command. It seems to want to make an fgb directory, which is weird.

These directories are now up to date and ready for testing:
/srv/imars-objects/fk/MEAN_7D_MODA/OC
/srv/imars-objects/fk/MEAN_7D_MODA/SST
/srv/imars-objects/fk/MEAN_7D_MODA/SST4


seashell 260 :/srv/imars-objects/fgb/MEAN_7D_MODA/SST4> rsync -hazv /srv/imars-objects/fk/MEAN_7D_MODA/OC/* ***@***.***/mnt/sdb/moda_oc_7d_fk/.
sending incremental file list
rsync: mkdir ***@***.***/mnt/sdb/moda_oc_7d_fk/." failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(576) [receiver=3.0.6]
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]
________________________________

**Comment by 7yl4r** [comment]
It looks like some of this got censored and that is making it hard for me to tell what has happened. Please email me the output directly.
