### ISSUE TITLE
Global L3 4km 8D datasets

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/erddap-config#45]
Let's add these datasets to our ERDDAP. These may be served via ERDDAP somewhere else?

Example filenames
chlor_a
AQUA_MODIS.20221024_20221031.L3m.8D.CHL.chlor_a.4km.nc

SST4
AQUA_MODIS.20151117_20151124.L3m.8D.SST4.sst4.4km.nc

nflh
AQUA_MODIS.20220930_20221007.L3m.8D.FLH.nflh.4km.nc

Rrs_667 (turbidity proxy)
AQUA_MODIS.20221016_20221023.L3m.8D.RRS.Rrs_667.4km.nc

**Comment by 7yl4r** [comment]
I am currently reading through erddap.com search results and updating [this gsheet](https://docs.google.com/spreadsheets/d/10vbzAxnexaF9vXJckQh03fNHWzsFaHNt9YkUmJAfnKo/edit#gid=1215704449)

**Comment by 7yl4r** [comment]
Seems like we ought to plan to generate and serve our own products, long-term. Let's take this effort one product at a time. Using USF RC's resources should pave the way to scaling up our processing and hosting significantly.
