### ISSUE TITLE
7D MEAN files not rsynced to dune

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/erddap-config#46]
I'm not sure when/how the GOM 7D MEAN files are supposed to rsync to dune. I have updated all the 7D mean files on my end, but I don't see them in the /mnt/sdb on dune.

/srv/imars-objects/gom/MEAN_7D_MODA/OC; SST4; SST 

and

/srv/imars-objects/gom/MEAN_7D_VSNPP/OC; SSTN; SST

**Comment by 7yl4r** [comment]
rsync is not working b/c file permissions from root_squash NFS settings.

gom served from cozumel, cozumel is not using puppet v3 yet. 

Steps to fix:

* [ ] cozumel updated puppet v3
* [x] no_root_squash setting for gom mount (implemented for all mounts b/c :shipit:)
* [ ] check on dune

**Comment by 7yl4r** [comment]
I was unable to get this fixed easily because cozumel is too old for puppet_v3 to be configured easily. We should switch the files served on cozumel over to tpa_pgs or the USF RC /work directories, then I can upgrade cozumel.

**Comment by 7yl4r** [comment]
I would like to try using a new location for the GoM files:

`/srv/imars-objects/tpa_pgs/rois/gom`

Let me know if you notice any performance differences vs the previous location (`/srv/imars-objects/gom`) or if you get permissions errors.

**Comment by dotis** [comment]
Ok. I'll move things over.
________________________________

**Comment by 7yl4r** [comment]
If all goes according to plan the new gom OC files will show up in ERDDAP Monday morning. Check the fgnms dashboard's OC maps to see if they are updated; currently they are ~30days out of date.

**Comment by dotis** [comment]
3.90M bytes/sec is the rate.
________________________________

**Comment by dotis** [comment]
Up to 17.75M bytes per sec now
________________________________

**Comment by 7yl4r** [comment]
I don't know how these speeds compare to what we were getting when running on IMaRS servers.

The cause of slowdowns could be due to network bandwidth or limitations on the physical disks in TPA.
We will need to contact USF-RC to debug.

The network connection is capped at 40Gb/s (or 10Gb/s?) and we can reasonably expect a disk speed topping at 6Gb/s.

**Comment by dotis** [comment]
I ran some things yesterday and the processing seemed to be moving at a normal speed. I think it may just be the i/o that was slow there. I'll have to test a bit more.
________________________________
