### ISSUE TITLE
set up gom dataset.xml files

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#47]
dataset           | status
------------------|--------------------
moda_oc_7d_gom    | working 
moda_sst4_7d_gom  | new dataset.xml
vsnpp_sstn_7d_gom | new dataset.xml
vsnpp_sst_7d_gom  | new dataset.xml
vsnpp_oc_7d_gom   | new dataset.xml

What I need for `docker exec -it erddap  bash -c "cd webapps/erddap/WEB-INF/ && bash GenerateDatasetsXml.sh -verbose"`

* type: EDDGridFromNcFiles
* dir: 
    * pattern: `/mnt/sdb/{sensor}_{product}_{temporal_resolution}_{roi}/` 
    * eg: `/mnt/sdb/moda_oc_7d_gom/`
* regex: .*\.nc

**Comment by 7yl4r** [comment]
waiting to see if ERDDAP server figures these out

**Comment by dotis** [comment]
I don't see that this is working. The dataset.xml for moda_sst4_7d_gom looks ok. The source attribute section of the file is grayed out. Not sure if that makes a difference.

**Comment by dotis** [comment]
Having the source attributes did not seem to help. I have grayed them out again. In the one working xml file (moda_oc_7d_gom), there are no source attributes in the file at all. Perhaps I should remove them altogether?

**Comment by dotis** [comment]
Created a new file https://github.com/USF-IMARS/erddap-config/blob/master/datasets/moda_sst4_7d_gom/dataset.xml

There were some differences between the working file (moda_oc_7d_gom) and the moda_sst4_7d_gom in the "axis variable" section. Let's see if this helps.

**Comment by dotis** [comment]
Still failing. I can't tell from the status page what the errors might be.

**Comment by 7yl4r** [comment]
I need to log in to erddap and run the DasDds.sh script on each failing dataset to debug them. I am going to open new issues for each failing dataset so that I get less confused.

**Comment by dotis** [comment]
Ok. Currently just trying to make moda_sst4_7d_gom work. Checking the input files to see if there are differences between the OC and SST4 for gom.

**Comment by 7yl4r** [comment]
I found an unrelated error in the erddap configuration that may have been preventing your updates from applying. 

The setup.xml had become malformed because of a git merge collision caused by the update cronjob. I don't know how that happened, but I have reset things and hoping it doesn't happen again.

**Comment by 7yl4r** [comment]
turns out all 4 of the datasets have the same issue: https://github.com/USF-IMARS/erddap-config/issues/48

**Comment by dotis** [comment]
moda_sst4_7d_gom is working. The title it shows is a bit weird: "USF data from a local source" rather than a descriptive title, but it's in there. It seems I need to change the dataset.xml files for the other datasets.

@7yl4r Can we add a moda_sst_7d_gom? Thanks.

**Comment by dotis** [comment]
I figured out how to change the title.

**Comment by dotis** [comment]
I made the title changes in the dataset.xml files for the two working datasets, but I don't see that the changes have taken effect yet. Does this take awhile? Or, perhaps I needed to change the title elsewhere as well.

**Comment by dotis** [comment]
I changed the xml for vsnpp_sst4_7d_gom and vsnpp_oc_7d_gom. Let's see if these work.

**Comment by dotis** [comment]
The xml have been updated for all six datasets. I also updated the product names. Will this work? Stay tuned!

**Comment by dotis** [comment]
Seems like all six datasets are working!

**Comment by dotis** [comment]
Number of failing datasets = 0
