### ISSUE TITLE
Files on dune, but not in ERDDAP

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/erddap-config#53]
The rsync to dune worked this morning, but the files are not on ERDDAP. These are GOM 7day OC and SST4 files. ERDDAP is around four files behind, so they don't appear on the dashboard.

**Comment by 7yl4r** [comment]
Something mysterious had gone wrong with the ERDDAP installation. The datasets.xml file somehow dismounted from the hypervisor to the docker container. 
I reset the container and now I believe the latest image is showing up (2023-09-09).
I used [this link to check the GOM SST](http://131.247.136.200:8080/erddap/griddap/moda_sst_7d_gom.graph?sst_median%5B(last)%5D%5B(31.0):(18.01288)%5D%5B(-98.0):(-78.51478)%5D&.draw=surface&.vars=longitude%7Clatitude%7Csst_median&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff).
