### ISSUE TITLE
add seascapes colorbar

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#54]
The seascapes product being mirrored from AOML requires a custom colorbar `Seascapes`. See message below for error from DasDds.sh:

```
*** An error occurred while trying to load noaa_aoml_seascapes_8day:
java.lang.RuntimeException: datasets.xml error on or before line #267: IllegalArgumentException: colorBarPalette=Seascapes must be one of BlackBlueWhite,
```

According to [ERDDAP docs on colorbars](https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#palettes):

-------------------------

You can add additional palettes to ERDDAP. You can make them yourself or find them on the web (for example, at [cpt-city](http://soliton.vm.bytemark.co.uk/pub/cpt-city/) (external link)) although you'll probably have to edit their format slightly to conform to ERDDAP's .cpt requirements. To get ERDDAP to use a new .cpt file, store the file in tomcat/webapps/erddap/WEB-INF/cptfiles (you'll need to do that for each new version of ERDDAP) and either:
* If you use the default messages.xml file: add the filename to the <palettes> tag in tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/messages.xml. If you do this, you need to do it every time you upgrade ERDDAP.
* If you use a custom messages.xml file: add the filename to the <palettes> tag in your custom messages.xml file: tomcat/content/erddap/messages.xml . If you do this, you only need to do it once (but there is other work to maintain a custom messages.xml file).

Then restart ERDDAP so ERDDAP notices the changes. An advantage of this approach is that you can specify the order of the palettes in the list presented to users. If you add a collection, we encourage you to add a prefix with the authors initials (e.g., "KT_") to the name of each palette to identify the collection and so that there can be multiple palettes which would otherwise have the same name.

-------------------

@dotis has emailed to request the `Seascapes.cpt` file.

**Comment by 7yl4r** [comment]
here are the contents of the cpt file:
```
0 0 0 153 1 0 0 153
1 0 14 161 2 0 14 161
2 0 29 169 3 0 29 169
3 0 43 177 4 0 43 177
4 0 58 186 5 0 58 186
5 0 72 194 6 0 72 194
6 0 87 202 7 0 87 202
7 0 101 210 8 0 101 210
8 0 115 219 9 0 115 219
9 0 130 227 10 0 130 227
10 0 144 236 11 0 144 236
11 0 159 244 12 0 159 244
12 16 177 217 13 16 177 217
13 51 187 178 14 51 187 178
14 85 197 138 15 85 197 138
15 120 207 99 16 120 207 99
16 155 217 60 17 155 217 60
17 190 226 21 18 190 226 21
18 210 226 0 19 210 226 0
19 215 212 0 20 215 212 0
20 219 201 0 21 219 201 0
21 223 189 0 22 223 189 0
22 227 178 0 23 227 178 0
23 231 166 0 24 231 166 0
24 235 155 0 25 235 155 0
25 239 143 0 26 239 143 0
26 243 131 0 27 243 131 0
27 247 120 0 28 247 120 0
28 251 108 0 29 251 108 0
29 255 96 0 30 255 96 0
30 50 50 50 31 50 50 50
31 125 125 125 32 125 125 125
32 200 200 200 33 200 200 200
B 0 0 0
F 255 255 255
N 128 128 128
```

**Comment by 7yl4r** [comment]
I have added the cpt file to the directory but (as expected) it is not working without the changes to the messages.xml. I am uncertain the best way to go about that.

**Comment by 7yl4r** [comment]
Fixed.

![image](https://github.com/USF-IMARS/erddap-config/assets/1051390/d4ec7d51-f21b-4691-89f8-1d1cd51514b9)

**Comment by 7yl4r** [comment]
Note that we are now using a custom messages.xml file, which may need manual updating whenever ERDDAP updates.

**Comment by dotis** [comment]
The labels on the color bar are not very good. I'm not sure what the issue is. It is the same on the NOAA Coastwatch site. I wonder if one could tweak the .cpt file.

**Comment by 7yl4r** [comment]
The fix here is to modify the default colorbar to include all possible class values [0-33]; the default is doing some weird rounding based on what values appear in the dataset. I think this means that either 0 or 33 never actually show up in the data.

ColorbarString: `Seascapes|||0|33|`
